name: Deploy Serverless Application

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: nodejs14.x

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: AKIASK5MCSQEZJ42R4ZV  # Using GitHub Secrets
        AWS_SECRET_ACCESS_KEY: 3g+oR0vdrd14/lhwjAeWJWDm6ak7bHeXABFw7x8g  # Using GitHub Secrets
        SERVERLESS_ACCESS_KEY: AK0O7eNtGPNrGn29QOoROH6eaKy5vzDEXEHX8zuHmXsdl  # Your Serverless Access Key if needed
      run: |
        serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
        serverless deploy --stage dev
